#print("Welcome to Aptech new office space")
#number1 = 30
#number2 = 60
#print(f'number1 + number2 = {number1 + number2}')

# print("Fill in the credentials;")
# name = input("Enter your name: ")
# age = int(input("Enter your age: "))
# print("******************")

# print("name: ", name)
# print("age: ", age)

# age = 19

# if age < 18: 
#     print("You are not adult")
# else:
#     print("Congratulations: You are an adult")

# num1 = int(input("Enter a number: "))
# num2 = int(input("Enter another number:"))
# operator = input("Enter an operator(+,-,*,/): ")

# if operator == "+":
#     print(f'The addition = {num1 + num2}')
# elif operator == "-":
#     print(f'The substraction = {num1 - num2}')
# elif operator == "*":
#     print(f'The multiplication = {num1 * num2}')
# elif operator == "/" and num1 < num2:
#     print("The first number must be greater than the second")
# elif operator == "/" and num1 >= num2:
#     print(f'The division = {num1 / num2}')
# else: 
#     print("You must select a valid operator")


# def front_back(str):
#     if(str[len(str)] <= 1 ):
#         return str
#     else: return str[-1] + str[1:-1] + str[0]

# sum only the odd numbers
# odd = int()
# for i in range(1, 11):
#     if(i % 2 != 0):
#         odd += i
# print(odd)


# total = 0
# while  True:
#     num = int(input("Enter number, 0 to Stop: "))
#     if num == 0:
#         break
#     total += num
# print(f"Sum = {total}")


# for i in range(1,6):
#     if i == 3 :
#         break
#     print(i)

# for i in range(1,6):
#     if i == 3 :
#         continue
#     print(i)
    
# for i in range(1,6):
#     if i == 3 :
#         pass
#     print(i)

# asterix = "*"
# for i in range(1, 13):
#     for j in range(1, 13):
#         result = i*j
#         print(f"{asterix * result}", end = "\t")   
#     print("")



# PYRAMID
# num = 10

# for i in range(num):
#     for j in range(num - i - 1):
#         print(" ", end = "")
#     for k in range(i + 1):
#         print("* ", end = "")
#     print()
    
# print("\n")

# # RIGHT ANGLE
   
# rows = 10

# for i in range(1, rows + 1):
#     for j in range(i):
#         print("*", end=" ")
#     print()

# print("\n")

# # RECTANGLE/SQUARE

# size = 10

# for i in range(size):
#     for j in range(size):
#         if i == 0 or i == size - 1 or j == 0 or j == size - 1:
#             print("*", end=" ")
#         else:
#             print(" ", end=" ")
#     print()
    
# print("\n")

# # HEART

# for i in range(6):
#     for j in range(7):
#         if ((i == 0 and j % 3 != 0) or (i == 1 and j % 3 == 0) or (i - j == 2) or (i + j == 8)):
#             print("*", end= " ")
#         else:
#             print(" ", end= " ")
#     print()


# def addTwo(a, b):
#     return a + b

# sum = addTwo(10, 20)
# print(f"Sum = {sum}")


# def greet():
#     print("Welcome to Aptech new office space")
    
# greet()
    
    
# def areaOfRectangle(length, width):
#     return length * width

# L = int(input("Enter the length of the rectangle: "))
# W = int(input("Enter the width of the rectangle: "))
# Area = areaOfRectangle(L, W)
# print(f"The area of the rectangle is: {Area}")


# def triangleBlock(n):
#     if n <= 1:
#         return n
#     else:
#         return n + triangleBlock(n - 1)
    
# print(triangleBlock(7))


        
# function to add all odd numbers inputed by the user
# def sumOfOddNumbers():
#     total = 0
#     while True:
#         num = int(input("Enter a number, 0 to Stop: "))
#         if num == 0:
#             break
#         elif num % 2 != 0:
#             total += num  
#     return f"Sum of odd numbers = {total}"

# print(sumOfOddNumbers())   


# a function that takes a number from a user from 1 to 5 and compares it with a random number generated by the computer and prints if the user wins or loses, use while loop and the program should terminate if 0 is inputed
# import random
# def guessTheNumber():
#     while True:
#         user_input = int(input("Enter a number between 1 and 5 (0 to stop): "))
#         if user_input == 0:
#             print("Game Over")
#             break
#         elif user_input < 1 or user_input > 5:
#             print("Please enter a valid number between 1 and 5.")
#             continue
        
#         computer_number = random.randint(1, 5)
#         if user_input == computer_number:
#             print("Congratulations! You guessed the correct number!")
#         else:
#             print(f"Sorry, the correct number was {computer_number}. Try again!")
    
    
# guessTheNumber()

# # a function to remove a duplicate from any given list
# def removeDuplicates(items):
#     result = []
#     for item in items:
#         if item not in result:
#             result.append(item)
#     return result


# list = [1, 2, 3, 4, 5, 2, 3, 6]
# print(removeDuplicates(list))

# # without using sort(), a simple loop function to print out the second largest number
# def secondLargest(nums):
#     if len(nums) < 2:
#         return "List must contain at least two numbers."
    
#     largest = 0
#     second_largest = 0
    
#     for num in nums:                                                                         
#         if num > largest:
#             second_largest = largest
#             largest = num
#         elif largest > num > second_largest:
#             second_largest = num

#     return second_largest

  
# numbers = [8, 1, 4, 1, 7, 9]
# print(f"The second largest number is: {secondLargest(numbers)}")